[package]
name = "k8sql"
version = "0.1.0"
authors = ["Dentrax <furkan.turkal@trendyol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
